### ISSUE TITLE
gitst.github.con

### ISSUE THREAD

**Issue by ddkwork** [feng2208/github-hosts#1]
请教大佬如何添加 gitst.github.con，Chrome命令正常，py返回404。谢谢大佬

**Comment by feng2208** [comment]
你说的是 gist.github.com 吧，这网站被拦截无法加速。

**Comment by ddkwork** [comment]
喔，谢谢



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 6, 2024 09:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [feng2208/github-hosts] gitst.github.con (Issue #1)




 
你说的是 gist.github.com 吧，这网站被拦截无法加速。

**Comment by ddkwork** [comment]
啊不对，用powershell启动Chrome并添加gist github可以访问的

**Comment by ddkwork** [comment]
![image](https://github.com/user-attachments/assets/a0c535e1-c538-4c8b-84ca-71e33fe06a0a)
奇怪，chrome可以访问，我又试了一下
